language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  
env:
secure: "flgQs7hTyf+yDHrCkm5IBbOBNiQ71xpJXOhVgxPFBiLLWSgpxLuGlbWtbA2vLRIvy6tvCy8q7BT9TBixxMwgu5AfvqVEWc3K/Oyn0o6jtEEwu4UsVbZKsuakdDVbwXSgvvaR0pod+bq0lhw+yQDTB4sOFjO09LsbhtLohaGAbHZQ5eF+DNswETkg2zBArJ8/b5Am8H4V31Q2vEsUMsVWyCFnOTY8vqbTy3aKEPjUZEovAMKr8FjZNWlJFDgLAncaUHL8ArFVqVZXyBO60dG+ZDHi79Rg7yNBGU2gM92WNZwhEO1egKr8OFCGfFfpWpOqbpC51a9Ra2CyLKE3zgb++c3gZkQ3ziKWFRf2qUU4/yEJwgheOitt1W9YXOt4cbsI+/W4Th2U4DsM9jtepICzkDCBBbMmqeINof8IrobZyfPZhLDw4sDiGfflnc9v4G1OWDR8JCF4CvjWpp642iBB1UiqO3Y8jLao3SteFFyoaqb6wVEPyoCBRjagvNavx08oKC5o6jeOyvQCLMKEwT9Wv6n9QSIMSgZgUb1H0TgbjQ7UnMzyOKivwj8e0wltDhHPrS5tg+L6NqME0g/F9n+bfHboNkKn/lXj0JkQtzLe2xrKtvXQlTlsOlQtNoND1o4VSfn6srM3bLmWoZ4FTe1H91gnTYXzi58qbNlqVEc7e70="
secure: "An9LS7Lj1P1wxXNqTtR074HwvIAOlsdZCP7/WkjJswFoHef+KOUJUGfqJEACACvIhTHy11jCEqJBjODmzoq2eKgdIzXSXzLzfebttPD0C4minZpfPP1MW48YiCk4TLXq97ybTVpcNgWS3cozixa6G4YZzTe8fASUiRlZSeVofvIoJF/nCMmKFpAmi7nqyP61beovXFiokbgtJIV4VB6mI/0HrqFa0EmHPer5VcU8QACgRX/fERPYWhLpIYf0Ah7v1ly52HqGom7AeAiJIWetDShA1aOBMLggJ0Gk+MbbJBj7Xco0877vSTsxmtWXtCCJgd2YYfB5qldwiDIUdJnlylDiRkbJIjLZjg5Im0/uFx0Lg5BMgizVnpyndahK+A0gtACD3Am9XPVFU5jHDiEZXk2qQvdwSugCpPasbYUwxo3OSULDsfN/TxoJ+jjWq/b2Q+v2zIEGHnpKlVQ1OY+PMQtrQpBAbJE9RdMVn6p2EXzWPX/Pll3sJMW/PiCj8usekpLk1T4wQSc1l1iAHrDC5JSaZd+8KUxMYe5FU41iXfkDICFQg0fi/tAw99F/WR9dGNMt+WMhAvdIcionymX4JcDW4koyW43u8SlyfHnxVL9+7pP5FoXbxmFcOih7NoTEO96PTl9QTpQpi4q2TgNLdmYoNfJh5EQLQitsdoPurck="